<Project>
  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), 'README.md'))\build\common.props" />
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <Description>A dotnet tool for mirroring nuget.org and downloading packages to disk.</Description>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>nugetmirror</ToolCommandName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="McMaster.Extensions.CommandLineUtils" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NuGet.CatalogReader\NuGet.CatalogReader.csproj" />
  </ItemGroup>

  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
