# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish to NuGet.org

on:
  workflow_dispatch:   # ↩️ manual trigger only

jobs:
  build-win:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: ./build.ps1
      shell: pwsh
    - name: Publish
      run: dotnet nuget push artifacts\nupkgs\*.nupkg  --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      shell: pwsh
